---
- name: Inventario
  hosts: localhost
  connection: local
  gather_facts: no
  vars:
    netbox_url: https://netbox.intertic.com.ar
    netbox_token: e6b8020fb8989adcd3f77d2cd5d332fe26fd5882
  tasks:
    - name: Get Devices
      uri:
        url: "{{ netbox_url }}/api/dcim/devices"
        method: GET
        headers:
          Authorization: "Token {{ netbox_token }}"
          Accept: 'application/json'
        return_content: yes
        body_format: json
        status_code: [200, 201]
        validate_certs: false
      register: netbox_devices
      run_once: yes
    - debug:
        var: netbox_devices
    
