---
- name: Download and install 7zip on Windows
  hosts: all
  gather_facts: no

  tasks:
  - name: Download the 7-Zip package
    win_get_url:
      url: https://www.7-zip.org/a/7z1701-x64.msi
      dest: C:\Windows\Temp\7z.msi

  - name: Install MSI
    win_package:
      path: C:\Windows\Temp\7z.msi
      state: present
